(source "elpy" "http://jorgenschaefer.github.io/packages/")
(source gnu)
(source marmalade)
(source melpa)

(depends-on "better-defaults")
(depends-on "cask")
(depends-on "company")
(depends-on "counsel")
(depends-on "doom-themes")
(depends-on "evil")
(depends-on "nlinum-relative")
(depends-on "org")
(depends-on "pallet")
